/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
<<<<<<< HEAD
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/attendant-login`; params?: Router.UnknownInputParams; } | { pathname: `/attendant-registration`; params?: Router.UnknownInputParams; } | { pathname: `/driver-profile`; params?: Router.UnknownInputParams; } | { pathname: `/driver-registration`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/parent-login`; params?: Router.UnknownInputParams; } | { pathname: `/parent-registration`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/registration`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/system` | `/system`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/attendant-login`; params?: Router.UnknownOutputParams; } | { pathname: `/attendant-registration`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-registration`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/map`; params?: Router.UnknownOutputParams; } | { pathname: `/parent-login`; params?: Router.UnknownOutputParams; } | { pathname: `/parent-registration`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/registration`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/system` | `/system`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/attendant-login${`?${string}` | `#${string}` | ''}` | `/attendant-registration${`?${string}` | `#${string}` | ''}` | `/driver-profile${`?${string}` | `#${string}` | ''}` | `/driver-registration${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `/parent-login${`?${string}` | `#${string}` | ''}` | `/parent-registration${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/registration${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/system${`?${string}` | `#${string}` | ''}` | `/system${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/attendant-login`; params?: Router.UnknownInputParams; } | { pathname: `/attendant-registration`; params?: Router.UnknownInputParams; } | { pathname: `/driver-profile`; params?: Router.UnknownInputParams; } | { pathname: `/driver-registration`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/parent-login`; params?: Router.UnknownInputParams; } | { pathname: `/parent-registration`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/registration`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/system` | `/system`; params?: Router.UnknownInputParams; };
=======
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/registration`; params?: Router.UnknownInputParams; } | { pathname: `/driver-registration`; params?: Router.UnknownInputParams; } | { pathname: `/parent-registration`; params?: Router.UnknownInputParams; } | { pathname: `/attendant-registration`; params?: Router.UnknownInputParams; } | { pathname: `/parent-login`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/attendant-login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/map` | `/map`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/registration`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-registration`; params?: Router.UnknownOutputParams; } | { pathname: `/parent-registration`; params?: Router.UnknownOutputParams; } | { pathname: `/attendant-registration`; params?: Router.UnknownOutputParams; } | { pathname: `/parent-login`; params?: Router.UnknownOutputParams; } | { pathname: `/map`; params?: Router.UnknownOutputParams; } | { pathname: `/attendant-login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/map` | `/map`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/registration${`?${string}` | `#${string}` | ''}` | `/driver-registration${`?${string}` | `#${string}` | ''}` | `/parent-registration${`?${string}` | `#${string}` | ''}` | `/attendant-registration${`?${string}` | `#${string}` | ''}` | `/parent-login${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `/attendant-login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/registration`; params?: Router.UnknownInputParams; } | { pathname: `/driver-registration`; params?: Router.UnknownInputParams; } | { pathname: `/parent-registration`; params?: Router.UnknownInputParams; } | { pathname: `/attendant-registration`; params?: Router.UnknownInputParams; } | { pathname: `/parent-login`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/attendant-login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/map` | `/map`; params?: Router.UnknownInputParams; };
>>>>>>> IT24103379
    }
  }
}
